### ISSUE TITLE
PhantomJS 2.1 has binary packages again

### ISSUE THREAD

**Issue by paulrutter** [fgrehm/docker-phantomjs2#2]
Since the release of 2.1, this dockerized version of PhantomJS is no longer needed, since we can now install the binary ourselves using the following Dockerfile command:

`
RUN npm install phantomjs-prebuilt
`
See https://www.npmjs.com/package/phantomjs-prebuilt.

Of course, this dockerized version was very useful because of the fact that there were no binaries yet. Thanks for the effort, though! 
I just wanted to let you know that there's an alternative available.

**Comment by Vanuan** [comment]
@paulrutter How does it work for you? I have the following:

```
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs)
```

You're probably missing the point of this repo. It is not a Dockerfile to download phantomjs from the official distribution. It is a Dockerfile to make phantomjs work with musl library which is a part of Alpine Linux.

In addition, phantomjs isn't linked with fontconfig and freetype statically, so those are still required to install.

**Comment by Vanuan** [comment]
With those packages:

```
RUN apk add freetype fontconfig
RUN apk --no-cache add ca-certificates
RUN wget https://github.com/andyshinn/alpine-pkg-glibc/releases/download/2.22-r5/glibc-2.22-r5.apk
RUN apk --allow-untrusted add glibc-2.22-r5.apk
```

Missing symbols are:

```
Error relocating /src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: backtrace: symbol not found
Error relocating /src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: backtrace_symbols: symbol not found
Error relocating /src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: __rawmemchr: symbol not found
```

**Comment by paulrutter** [comment]
You're right @Vanuan. I thought phantomjs-prebuilt was a good alternative, but it turns out that it isn't.
I've requested PhantomJS as a package for [AlpineLinux](https://bugs.alpinelinux.org/issues/4664); that would really solve the need for this dockerized version.
I'll close this issue, as turns out that it's not valid.

**Comment by Vanuan** [comment]
Also see https://github.com/andyshinn/alpine-pkg-glibc/issues/13
